Squashed commit of the following:
luxteam/rpr_pipelines pull request #1053
Opened 2022-05-26 18:35 UTC by Whatislove118

Jira Ticket
https://luxproject.luxoft.com/jira/browse/STVCIS-2909

Purpose
Auto job for WebUSD build&deploy process

⚠️ Notes for Reviewers
:octocat: Related PR'S
Jenkins Builds

2022-05-27 06:14 UTC, Speedwag00n requested changes

2022-05-27 06:14 UTC, Speedwag00n commented on vars/radeonpro_webusdviewer_pipeline.groovy
> +                zip archive: true, dir: "Build/Install", glob: '', zipFile: "WebUsdViewer_Windows.zip"
Насколько это тяжелый артефакт?

2022-05-27 06:14 UTC, Speedwag00n commented on vars/radeonpro_webusdviewer_pipeline.groovy
> +            script: "curl --insecure https://172.31.0.91/deploy?configuration=${options.deployEnvironment}",
IP захардкожен. Нужно его подкладывать из кредов Jenkins (WebUsdDockerRegisterHost)

2022-05-27 06:14 UTC, Speedwag00n commented on vars/webusd_set_env.groovy
> +            filename = "/home/user/JN/.envs/webusd.env.${options.deployEnvironment}"
Лучше положить его на NAS и выкачивать от туда. Так не забудем про него, если появится новая машина

2022-05-30 08:38 UTC, Whatislove118 commented on vars/radeonpro_webusdviewer_pipeline.groovy
> +                zip archive: true, dir: "Build/Install", glob: '', zipFile: "WebUsdViewer_Windows.zip"
Не очень (гб 1-2), просто Саши он вообще не нужен, и крайне редко когда понадобиться. Поэтому я и сделал его в виде доп опции.

2022-06-08 09:47 UTC, Speedwag00n commented on vars/radeonpro_webusdviewer_pipeline.groovy
> +                zip archive: true, dir: "Build/Install", glob: '', zipFile: "WebUsdViewer_Windows.zip"
Раз он измеряется в Гб, лучше этот артефакт архивировать с помощью 7zip на машине, а после сохранять
Функция zip в Jenkins работает не очень оптимально. Она сперва перекачивает не сжатые данные с ноды на сервер, на сервере их сжимает и сохраняет, как артефакт, если нужно

2022-06-08 09:48 UTC, Speedwag00n approved these changes

2022-06-08 10:34 UTC, merged