Squashed commit of the following:
luxteam/rpr_pipelines pull request #1070
Opened 2022-06-13 12:05 UTC by Whatislove118

### Jira Ticket
https://luxproject.luxoft.com/jira/browse/STVCIS-3062

### Purpose 
Add logic for notifications by Telegram Bot

### Effect of change

### Technical steps

### :warning: Notes for Reviewers

### :octocat: Related PR'S

### Jenkins Builds

2022-06-19 11:55 UTC, Speedwag00n requested changes

2022-06-19 11:55 UTC, Speedwag00n commented on vars/radeonpro_webusdviewer_pipeline.groovy
> +        sh "mv ./WebUsdWebServer/webusd.env.${options.deployEnvironment} ./WebUsdWebServer/.env.production"
Почему бы сразу не скачивать директорию с NAS в нужную директорию через downloadFiles?

2022-06-19 11:55 UTC, Speedwag00n commented on vars/radeonpro_webusdviewer_pipeline.groovy
> +                            throw new Exception()
Лучше сообщить конкретную ошибку, что какой-то определенный контейнер не запущен + вывести ее в лог

2022-06-19 11:55 UTC, Speedwag00n commented on vars/radeonpro_webusdviewer_pipeline.groovy
>                  throw new Exception()
Тут тоже лучше сообщить конкретную ошибку в сообщении Exception вместо пустого Exception

2022-06-19 11:55 UTC, Speedwag00n commented on vars/radeonpro_webusdviewer_pipeline.groovy
> +                    throw new Exception()
Тут тоже лучше сообщить конкретную ошибку в сообщении Exception вместо пустого Exception

2022-06-19 11:55 UTC, Speedwag00n commented on vars/radeonpro_webusdviewer_pipeline.groovy
> +    Boolean is_pr = false
```suggestion
    Boolean is_pr = env.CHANGE_URL == null
```

2022-06-19 11:55 UTC, Speedwag00n commented on vars/radeonpro_webusdviewer_pipeline.groovy
> +    String branchName = options.projectBranch
```suggestion
    String branchName = env.CHANGE_URL ?: options.projectBranch
```

2022-06-19 11:55 UTC, Speedwag00n commented on vars/radeonpro_webusdviewer_pipeline.groovy
> +    String status_message = "Success"
```suggestion
    String status_message = status ? "Success" : "Failed"
```

2022-06-19 11:55 UTC, Speedwag00n commented on vars/radeonpro_webusdviewer_pipeline.groovy
> +            script: "curl -X POST ${tgBotHost}/auto/notifications -H 'Content-Type: application/json' -d '{\"status\":\"${status_message}\",\"build_url\":\"${env.BUILD_URL}\", \"branch_url\": \"${bra
Лучше вынести в отдельную функцию в этом пайплайне

2022-06-20 13:31 UTC, Whatislove118 commented on vars/radeonpro_webusdviewer_pipeline.groovy
> +        sh "mv ./WebUsdWebServer/webusd.env.${options.deployEnvironment} ./WebUsdWebServer/.env.production"
Если можно указывать имя файла при скачке - то было бы ок, но я не нашел как это сделать, поэтому в 2 шага (в 1 скачиваем , во 2 переименовываем)

2022-06-24 07:16 UTC, Speedwag00n approved these changes

2022-06-24 07:16 UTC, Speedwag00n commented on vars/radeonpro_webusdviewer_pipeline.groovy
> +        sh "mv ./WebUsdWebServer/webusd.env.${options.deployEnvironment} ./WebUsdWebServer/.env.production"
Мм, да, это папка. Сразу задать имя не получится. Пусть останется текущий вариант

2022-06-27 14:14 UTC, merged