Implement pipeline for plugin version updating
luxteam/rpr_pipelines pull request #1700
Opened 2023-06-21 13:27 UTC by Sofshik

### Jira Ticket
https://luxproject.luxoft.com/jira/browse/STVCIS-3935

### Jenkins Builds
https://rpr.cis.luxoft.com/job/DevJobs/job/VersionIncrement/

2023-06-21 15:15 UTC, Speedwag00n commented on vars/increment_version.groovy
> +        currentBuild.description += "<b>Old ${toolName} version:</b> ${version}<br/>"
Нужно поправить отображение версии в описании билда, там она сейчас с запятыми и пробелами между частями, а не с точками

Old RadeonProRenderBlenderAddon version: 3, 6, 4

2023-06-21 15:19 UTC, Speedwag00n commented on vars/increment_version.groovy
> +            node("Windows && PreBuild") {
Нужно добавить ретраи
Иногда машина может по тем или иным причинам стать недоступна в процессе работы пайплайна. Тогда нужно попробовать выбрать другую машину и попробовать выполнить на них все тоже самое еще раз

Пример можно посмотреть тут
https://github.com/luxteam/rpr_pipelines/blob/master/vars/baseline_updater_pipeline.groovy#L385

2023-06-21 15:21 UTC, Speedwag00n commented on vars/increment_version.groovy
> +                    toolParams.("${projectRepo}").toolName,
Это map (аналог словаря из Python). Лучше обращаться к нему так
```suggestion
                    toolParams["${projectRepo}"].toolName,
```

2023-06-21 15:26 UTC, Speedwag00n commented on vars/increment_version.groovy
> +                version = version_read(versionPath, prefix, delimiter, "true").replace(', ', '.')
Для RPR Blender сейчас все равно отображаются запятые с пробелами в строке со старой версией
Old RadeonProRenderBlenderAddon version: 3, 6, 4
https://rpr.cis.luxoft.com/job/DevJobs/job/VersionIncrement/13/

2023-06-21 15:27 UTC, Speedwag00n requested changes
Some changes are required

2023-06-22 07:49 UTC, Speedwag00n approved these changes

2023-06-26 11:45 UTC, Sofshik commented
RPR Blender:
https://rpr.cis.luxoft.com/view/Blender%20+%20Maya/job/RPR-BlenderPlugin-Manual/6935/
https://rpr.cis.luxoft.com/view/Blender%20+%20Maya/job/RPR-BlenderPlugin-Manual/6949/

RPR Maya:
https://rpr.cis.luxoft.com/view/Blender%20+%20Maya/job/RPR-MayaPlugin-Manual/6099/
https://rpr.cis.luxoft.com/view/Blender%20+%20Maya/job/RPR-MayaPlugin-Manual/6105/

Render Studio:
https://rpr.cis.luxoft.com/job/RenderStudio-Manual/1617/
https://rpr.cis.luxoft.com/job/RenderStudio-Manual/1622/

USD Blender:
https://rpr.cis.luxoft.com/view/Blender%20+%20Maya/job/USD-BlenderPlugin-Manual/1246/
https://rpr.cis.luxoft.com/view/Blender%20+%20Maya/job/USD-BlenderPlugin-Manual/1247/

USD Maya:
https://rpr.cis.luxoft.com/view/Blender%20+%20Maya/job/USD-MayaPlugin-Manual/461/
https://rpr.cis.luxoft.com/view/Blender%20+%20Maya/job/USD-MayaPlugin-Manual/474/

USD Houdini:
https://rpr.cis.luxoft.com/view/Anari%20+%20Houdini/job/USD-HoudiniPlugin-Manual/1362/
https://rpr.cis.luxoft.com/view/Anari%20+%20Houdini/job/USD-HoudiniPlugin-Manual/1363/

RPR Anari:
https://rpr.cis.luxoft.com/view/Anari%20+%20Houdini/job/RPR-Anari-Manual/163/
https://rpr.cis.luxoft.com/view/Anari%20+%20Houdini/job/RPR-Anari-Manual/165/

USD Inventor:
https://rpr.cis.luxoft.com/view/Inventor%20+%20USDViewer/job/USD-InventorPlugin-Manual/371/
https://rpr.cis.luxoft.com/view/Inventor%20+%20USDViewer/job/USD-InventorPlugin-Manual/372/

2023-06-26 12:06 UTC, Speedwag00n commented
В Houdini, Anari и Inventor версия уезжает на новую строку
https://rpr.cis.luxoft.com/view/Inventor%20+%20USDViewer/job/USD-InventorPlugin-Manual/372/
https://rpr.cis.luxoft.com/view/Anari%20+%20Houdini/job/RPR-Anari-Manual/165/
https://rpr.cis.luxoft.com/view/Anari%20+%20Houdini/job/USD-HoudiniPlugin-Manual/1363/

2023-06-26 12:28 UTC, Speedwag00n requested changes

2023-06-26 12:28 UTC, Speedwag00n commented on vars/increment_version.groovy
> +//        git add version.h
Это комментарий-напоминание

1. Перед мерджем это нужно будет расскомментировать
2. Вызывать git add с файлом/файлами по пути versionPath, т.к. в каждой туле файлы отличаются

2023-06-26 12:28 UTC, Speedwag00n commented on vars/increment_version.groovy
> +        }
Этот код дублирует код со строк 156-162. Можно сделать Closure и вызывать его
https://www.baeldung.com/groovy-closures

2023-06-26 12:28 UTC, Speedwag00n commented on vars/increment_version.groovy
> +                if (!toolParams.keySet().contains(projectRepo)) {
Стоит оставить комментарий, что этот if нужен в случае сабмодулей RenderStudio

2023-06-26 12:28 UTC, Speedwag00n commented on vars/increment_version.groovy
> +                                if (!toolParams.keySet().contains(projectRepo)) {
Стоит оставить комментарий, что этот if нужен в случае сабмодулей RenderStudio

2023-06-26 12:28 UTC, Speedwag00n commented on vars/render_studio.groovy
> +                """
Актуально для всех пайплайн: код формирования кнопок в описании везде похожий.
Лучше сформировать отдельную функцию в increment_version и вызывать ее для обновления описания билда
Вызвать ее можно будет так: increment_version.my_function_name(...)

2023-06-26 12:28 UTC, Speedwag00n commented on vars/increment_version.groovy
> +def call(String projectRepo = "RPR Blender", String toIncrement = "Patch", Boolean fromPipeline = false) {
Функция может возвращать итоговую версию после обновления. Это позволит не читать повторно обновленную версию в пайплайнах

2023-06-26 16:47 UTC, Sofshik commented
https://rpr.cis.luxoft.com/view/Inventor%20+%20USDViewer/job/USD-InventorPlugin-Manual/373/
https://rpr.cis.luxoft.com/view/Anari%20+%20Houdini/job/USD-HoudiniPlugin-Manual/1365/
https://rpr.cis.luxoft.com/view/Anari%20+%20Houdini/job/RPR-Anari-Manual/167/

2023-06-28 06:14 UTC, Speedwag00n submitted a review, later dismissed

2023-06-28 06:28 UTC, Speedwag00n approved these changes

2023-06-28 06:28 UTC, merged