Psergeev/driver selection
luxteam/rpr_pipelines pull request #1729
Opened 2023-07-14 10:14 UTC by mark-rom

### Jira Ticket
https://luxproject.luxoft.com/jira/browse/STVCIS-3272

### Purpose

### Effect of change

### Technical steps
- [x] Step 1
- [x] Step 2
- [ ] Step 3

### :warning: Notes for Reviewers

### :octocat: Related PR'S

### Jenkins Builds
no driver version
https://rpr.cis.luxoft.com/job/DevJobs/job/StreamingSDKDriver/46/
private driver
https://rpr.cis.luxoft.com/job/DevJobs/job/StreamingSDKDriver/77/ (only one machine fits)
public driver
https://rpr.cis.luxoft.com/job/DevJobs/job/StreamingSDKDriver/42/
other value
https://rpr.cis.luxoft.com/job/DevJobs/job/StreamingSDKDriver/78/

2023-07-16 11:26 UTC, mark-rom commented on vars/driversSelection.groovy
> +        utils.unzip(this, "${workdir}\\${archiveName}")
unzip нужно перенести в downloadDriverOnWindows, чтобы можно было единую функцию использовать в preBuild стадии и тут для скачивания драйвера

2023-07-17 12:36 UTC, mark-rom commented on vars/driversSelection.groovy
> +        utils.unzip(this, "${workdir}\\${archiveName}")
перенес в новом пуше

2023-07-21 15:24 UTC, Speedwag00n requested changes
Также нужно сделать так, чтобы логи установки драйвера попадали в соответствующую директорию в артефактах. Сейчас они попают в корень и логи с разных машин будут друг друга перетирать. Как это сделать, можно посмотреть тут
https://github.com/luxteam/rpr_pipelines/blob/master/vars/amfdev_streaming_sdk.groovy#L541C1-L541C1
![1028](https://github.com/luxteam/rpr_pipelines/assets/49859594/a347c27e-720e-40a9-8560-7d929bedec4b)

2023-07-21 15:24 UTC, Speedwag00n commented on vars/driversSelection.groovy
> +            status = bat(returnStatus: true, script: "python ${CIS_TOOLS}\\driver_detection\\parse_driver.py --os win --html_path page.html \
Если статус не нулевой, лучше кинуть исключение прямо здесь

2023-07-21 15:24 UTC, Speedwag00n commented on vars/driversSelection.groovy
> +            if (status == 0) {
Тут проверка не понадобится после этого изменения
https://github.com/luxteam/rpr_pipelines/pull/1729/files#diff-7bfebc9270a8b3d5ad027012ef8b874fc2a7924c5e0f0358847759dccb827dc8R102

2023-07-21 15:24 UTC, Speedwag00n commented on vars/driversSelection.groovy
> +            if (status == 0) {
Тут проверка не понадобится после этого изменения
https://github.com/luxteam/rpr_pipelines/pull/1729/files#diff-7bfebc9270a8b3d5ad027012ef8b874fc2a7924c5e0f0358847759dccb827dc8R102

2023-07-21 15:24 UTC, Speedwag00n commented on vars/driversSelection.groovy
> +                // pass this case
```suggestion
                // driver failed environment clearing, ignore this error
```

2023-07-21 15:24 UTC, Speedwag00n commented on vars/driversSelection.groovy
> +            if (installationResultLogContent.contains("32 remove_all")) {
Есть ли более точная строка с ошибкой?
32 remove_all даже не содержит никаких ключевых слов указывающих на то, что это ошибка

2023-07-21 15:24 UTC, Speedwag00n commented on vars/driversSelection.groovy
> +            }
В лог ошибка может не попасть, если инсталлер крашнется. Тогда эта логика не отловит ошибку. Лучше кидать эксепшен всегда 

```suggestion
            } else {
                throw e
            }
```

2023-07-21 15:24 UTC, Speedwag00n commented on vars/driversSelection.groovy
> +        try{
```suggestion
        try {
```

2023-07-21 15:24 UTC, Speedwag00n commented on vars/driversSelection.groovy
> +                bat "Setup.exe -INSTALL -BOOT -LOG ${env.WORKSPACE}\\drivers\\amf\\stable\\tools\\tests\\StreamingSDKTests\\installation_result_${computer}.log"
По сути это копипаста со строк 123-125. Только путь до инсталлера отличается. Лучше сделать из этого небольшую функцию

2023-07-21 15:24 UTC, Speedwag00n commented on vars/driversSelection.groovy
> +                    utils.reboot(this, isUnix() ? "Unix" : "Windows")
Эту логику лучше перенести в installDriverOnWindows

2023-07-21 15:24 UTC, Speedwag00n commented on vars/driversSelection.groovy
> +                    throw new Exception("Unknown exit code")
Эту логику лучше перенести в downloadDriverOnWindows
https://github.com/luxteam/rpr_pipelines/pull/1729/files#diff-7bfebc9270a8b3d5ad027012ef8b874fc2a7924c5e0f0358847759dccb827dc8R102

2023-07-21 15:24 UTC, Speedwag00n commented on vars/driversSelection.groovy
> +            } catch(e) {}
```suggestion
            archiveArtifacts "*.log, *.LOG", allowEmptyArchive: true
```

2023-07-21 15:24 UTC, Speedwag00n commented on vars/driversSelection.groovy
> +            currentBuild.result = "FAILURE";
Эту строку нужно удалить. Фейл выставит логика ретраев, если будет нужно

2023-07-21 15:24 UTC, Speedwag00n commented on vars/driversSelection.groovy
> +        println("[INFO] Parameter revisionNumber was not set. No driver will be installed on ${computer}")
На пребилде пишется
Parameter revisionNumber was not set. No driver will **be installed on preBuild**
Лучше заменить просто на. И так понятно, что если он не выставлен, он нигде не выставлен
Parameter revisionNumber was not set

2023-07-21 15:41 UTC, mark-rom commented on vars/driversSelection.groovy
> +            } catch(e) {}
А расскажи про это подробнее, пожалуйста

2023-07-21 15:43 UTC, mark-rom commented on vars/driversSelection.groovy
> +            if (installationResultLogContent.contains("32 remove_all")) {
Полная строка выглядит так "Deleting C:\Users\user\AppData\Local\Temp\AMDRSInstaller failed with error code 32 remove_all: The process cannot access the file because it is being used by another process.: "C:\Users\user\AppData\Local\Temp\AMDRSInstaller""
Эту часть сроки я взял, чтобы разделять с другими ошибками из лога. Если мы убираем ту логику, то я думаю, нужно оставить "error code 32 remove_all"

2023-07-24 11:51 UTC, mark-rom commented on vars/amfdev_streaming_sdk.groovy
> +    String revisionNumber = ""
done

2023-07-24 11:51 UTC, mark-rom commented on vars/driversSelection.groovy
> +    static final REVISION_NUMBER_PATTERN = ~/^\d{2}\.\d{1,2}\.\d$/
done

2023-07-24 11:51 UTC, mark-rom commented on vars/driversSelection.groovy
> +def status, driverPath, dirName
done

2023-07-24 11:52 UTC, mark-rom commented on vars/driversSelection.groovy
> +def updateDriver(revisionNumber, osName, computer, driverVersion){
done

2023-07-24 11:52 UTC, mark-rom commented on vars/driversSelection.groovy
> +                    utils.reboot(this, isUnix() ? "Unix" : "Windows")
done

2023-07-24 11:52 UTC, mark-rom commented on vars/driversSelection.groovy
> +                    throw new Exception("Unknown exit code")
done

2023-07-24 11:52 UTC, mark-rom commented on vars/driversSelection.groovy
> +            currentBuild.result = "FAILURE";
done

2023-07-24 11:52 UTC, mark-rom commented on vars/driversSelection.groovy
> +            } catch(e) {}
done

2023-07-24 11:52 UTC, mark-rom commented on vars/driversSelection.groovy
> +        return ".//${dirName}"
done

2023-07-24 11:52 UTC, mark-rom commented on vars/driversSelection.groovy
> +            status = bat(returnStatus: true, script: "python ${CIS_TOOLS}\\driver_detection\\parse_driver.py --os win --html_path page.html \
done

2023-07-24 11:52 UTC, mark-rom commented on vars/driversSelection.groovy
> +            if (status == 0) {
done

2023-07-24 11:52 UTC, mark-rom commented on vars/driversSelection.groovy
> +            if (installationResultLogContent.contains("32 remove_all")) {
done

2023-07-24 11:53 UTC, mark-rom commented on vars/driversSelection.groovy
> +                // pass this case
done

2023-07-24 11:53 UTC, mark-rom commented on vars/driversSelection.groovy
> +            }
done

2023-07-24 11:53 UTC, mark-rom commented on vars/driversSelection.groovy
> +        try{
done

2023-07-24 11:53 UTC, mark-rom commented on vars/driversSelection.groovy
> +            if (status == 0) {
done

2023-07-24 11:53 UTC, mark-rom commented on vars/driversSelection.groovy
> +                bat "Setup.exe -INSTALL -BOOT -LOG ${env.WORKSPACE}\\drivers\\amf\\stable\\tools\\tests\\StreamingSDKTests\\installation_result_${computer}.log"
done

2023-07-24 11:53 UTC, mark-rom commented on vars/driversSelection.groovy
> +    if (revisionNumber != "") {
done

2023-07-24 11:53 UTC, mark-rom commented on vars/driversSelection.groovy
> +        println("[INFO] Parameter revisionNumber was not set. No driver will be installed on ${computer}")
done

2023-07-24 11:53 UTC, mark-rom commented on vars/getProposedDriverVersion.groovy
> +def getDriverVersionOnWindows(revisionNumber, computer) {
done

2023-07-24 17:09 UTC, mark-rom commented
RE: https://github.com/luxteam/rpr_pipelines/pull/1729#pullrequestreview-1541244550
Изменил логику так, чтобы логи драйверов собирались вместе с остальными логами тестов.
Внес изменения, указанные в ревью

2023-07-25 06:10 UTC, Speedwag00n requested changes
Также нужны свежие билды

2023-07-25 06:10 UTC, Speedwag00n commented on vars/driversSelection.groovy
> +    timeout(time: "60", unit: "MINUTES") {
```suggestion
    timeout(time: "20", unit: "MINUTES") {
```

2023-07-25 06:10 UTC, Speedwag00n commented on vars/driversSelection.groovy
> +    def setupDir
Переменную можно объявить здесь
https://github.com/luxteam/rpr_pipelines/pull/1729/files#diff-7bfebc9270a8b3d5ad027012ef8b874fc2a7924c5e0f0358847759dccb827dc8R16

2023-07-25 09:20 UTC, mark-rom commented on vars/amfdev_streaming_sdk.groovy
> +            utils.moveFiles(this, osName, "*.log, *.LOG", ".")
Здесь я затупил и не посмотрел при изменении на формат

2023-07-25 09:20 UTC, mark-rom commented on vars/driversSelection.groovy
> +    timeout(time: "60", unit: "MINUTES") {
done

2023-07-25 09:20 UTC, mark-rom commented on vars/driversSelection.groovy
> +    def setupDir
done

2023-07-25 11:22 UTC, Speedwag00n approved these changes

2023-07-26 16:11 UTC, merged