Psergeev/streaming tools overview report
luxteam/rpr_pipelines pull request #1846
Opened 2023-10-17 14:44 UTC by mark-rom

### Jira Ticket

### Purpose

### Effect of change

### Technical steps
- [x] Step 1
- [x] Step 2
- [ ] Step 3

### :warning: Notes for Reviewers

### :octocat: Related PR'S

### Jenkins Builds

2023-10-18 09:23 UTC, Speedwag00n requested changes

2023-10-18 09:23 UTC, Speedwag00n commented on vars/utils.groovy
> +                                    self.bat """
Оставь TODO на будущее, что нужно переделать

2023-10-18 12:55 UTC, mark-rom commented on vars/utils.groovy
> +                                    self.bat """
done

2023-11-13 08:41 UTC, Speedwag00n requested changes

2023-11-13 08:41 UTC, Speedwag00n commented on vars/amfdev_streaming_sdk.groovy
> +    return "${options.osName} && ${options.MULTICONNECTION_CLIENT_TAG}"
Нужно убрать эти изменения перед мерджем

2023-11-13 08:41 UTC, Speedwag00n commented on vars/multiplatform_pipeline.groovy
> -                        testerLabels = "${osName} && Tester && gpu${asicName} && !Disabled"
Нужно убрать эти изменения перед мерджем

2023-11-13 08:41 UTC, Speedwag00n commented on vars/amfdev_streaming_sdk.groovy
> +    Boolean streamingTools = false
Сможем заменить на проверку наличия нужные групп в списке групп?

2023-11-23 06:47 UTC, Speedwag00n approved these changes

2023-11-24 07:12 UTC, merged