GitHub notifications
luxteam/rpr_pipelines pull request #241
Opened 2020-08-19 14:06 UTC by Speedwag00n

### Jira Ticket
* https://adc.luxoft.com/jira/browse/STVCIS-543
### Purpose
* Implement Github notifications for represent current state of PR on github page of building PR
### Effect of change
* Create checks for each stage of build and update them during build (implemented for Blender, Maya, Max, Core and Viewer)
### Technical steps
- [x] Initialize on PreBuild status checks for all stages which will be executed later (Build stages, Test stages and Deploy stage).
- [x] During build update status checks: pending status for stages which are in progress or will be executed later, success status for stages which were successfully finished, failed status for stages which failed with some exception and they will be retried, error status for stages which failed with some exception and won't be retried (exceeded all attempts).
- [x] If build was aborted all non-success status checks will be marked as errored with message about build aborting.
- [x] If build stage was failed at all Test stages for this OS will be marked as errored with message about failed building.
### :warning: Notes for Reviewers
* This PR contains commits from branch "inemankov/build status"
### Jenkins Builds
* Will be added after release

2020-08-20 15:57 UTC, Kataderon requested changes
Пересекается с https://github.com/luxteam/rpr_pipelines/pull/242/
Иметь несколько pr'ов с одними и теми же изменениями плохая практика

2020-08-20 16:29 UTC, Speedwag00n commented
> 
> 
> Пересекается с #242
> Иметь несколько pr'ов с одними и теми же изменениями плохая практика

Создам отдельную ветку без изменений из ПРа по сбору ошибок и создам новый ПР

2020-08-21 08:11 UTC, Speedwag00n commented
Вырезал из этого коммита изменения, внесенные в рамках 242 ПРа настолько, насколько возможно (этот ПР зависит от 242 ПРа, т.к. во многом использует схожие способы сбора ошибок)
Прогоны запущу на выходных и включу их в ПР

2020-08-26 15:40 UTC, MagisterDemens approved these changes
Я думаю, для автоджоб в которых будет использоваться данный класс, надо добавлять параметр
❗ ![image](https://user-images.githubusercontent.com/11044999/91324666-f9e27780-e7ca-11ea-9d31-ed1d5932fcf4.png)

И наверное, стоит добавить еще 1 статус - итоговый статус билда. Чтобы в явном виде писать, что N кейсов не совпала с бейзлайном.
@epozine согласен?

2020-08-26 16:10 UTC, epozine commented
У меня есть несколько вопросов к данному ПРу. 
1. Насколько подробно мы хотим писать статус каждой стадии? Запрос был на конкретную причину, а не общую формулировку "Build was failed". Будет ли написано, что не выкачан репозиторий например? 
2. В коре мы не собираем плагин, возможно ли писать кастомные надписи в джобах? Мы там выкачиваем бинари же только. Звучит некорректно, что построение прошло успешно.
3. В максе, в случае когда упал билд, у нас успешно построен отчет. Вопрос общий, а нужно ли вообще строить какие-либо отчеты полные, если билд не собирается? Мне кажется нет. Достаточно будет причины падения билда, если упал именно код самого построения, то можно ссылку на лог приложить например.

2020-08-26 16:10 UTC, epozine commented
> Я думаю, для автоджоб в которых будет использоваться данный класс, надо добавлять параметр
> ❗ ![image](https://user-images.githubusercontent.com/11044999/91324666-f9e27780-e7ca-11ea-9d31-ed1d5932fcf4.png)
> 
> И наверное, стоит добавить еще 1 статус - итоговый статус билда. Чтобы в явном виде писать, что N кейсов не совпала с бейзлайном.
> @epozine согласен?

Я думаю это в деплой стадии можно написать, что пройдено столько-ко тестов, завалено столько-то и тд

2020-08-26 16:14 UTC, epozine commented
Первый вопрос отпадает, нашел ответ в коде. "Failure during plugin build" звучит как общая формулировка, но означает непосредственно что упала сборка исходного кода.

2020-08-26 16:24 UTC, Speedwag00n commented
1. Для каждой стадии билда передается несколько состояние в нескольких ключевых точках. Например, Clonning plugin repository -> Building plugin -> Saving artifacts. Примерно на каждую такую точку есть свое сообщение об ошибке. Тут, например, ошибка о том, что не удалось выкачать плагин: https://github.com/luxteam/rpr_pipelines/blob/ef0251097aeadeb14866c38f8016b6a4a2521aa5/vars/rpr_blender28plugin_pipeline.groovy#L592
2. Все сообщения задаются вручную в пайплайнах, их можно поменять. Заменю слово Build в пайлпайне коры на Prepare.
3. На мой взгляд, status check для Deploy стадии должен описывать только ее и ничего больше. Если построился отчет, пускай и с потерянными группами, он все же есть.
Для status checks билд стадии можно сразу получить плагин, если он собрался успешно, кликнув на 'Details'. Если билд упал, там будет лог (это уже реализовано). Пример (достаточно кликнуть на Details напротив status check Build стадии), https://github.com/Speedwag00n/RadeonProRenderMaxPlugin/pull/1

2020-08-26 16:42 UTC, epozine reviewed
Косметические предложения

2020-08-26 16:42 UTC, epozine commented on vars/rpr_core_pipeline.groovy
> +                GithubNotificator.updateStatus("Test", options['stageName'], "pending", env, options, "Executing tests", "${BUILD_URL}")
Может добавить тестовую группу, которую мы запускаем? Full/regression например.

2020-08-26 16:42 UTC, epozine commented on vars/rpr_core_pipeline.groovy
> +            String errorMessage = e.getMessage()?:"Unknown reason"
```suggestion
            String errorMessage = e.getMessage()?:"The reason is not automatically identified, please contact support."
```

2020-08-26 16:42 UTC, epozine commented on vars/rpr_core_pipeline.groovy
> +            String errorMessage = e.getMessage()?:"Unknown reason"
Неизвестная причина звучит не очень корректно на мой взгляд. Я предлагаю такой вариант формулировки.

2020-08-26 16:42 UTC, epozine commented on vars/rpr_core_pipeline.groovy
> +            String errorMessage = e.getMessage()?:"Unknown reason"
Для CIS команды Unknown reason звучит понятно, что просто система не нашла ошибка и она где-то вот тут. А для человека с гитхаба выглядит как-то странно.

2020-08-26 16:42 UTC, epozine commented on vars/rpr_core_pipeline.groovy
> +                GithubNotificator.updateStatus("Test", options['stageName'], "failure", env, options, "Some tests were marked as error", "${BUILD_URL}")
```suggestion
                GithubNotificator.updateStatus("Test", options['stageName'], "failure", env, options, "Some tests were marked as error. Check the report for details.", "${BUILD_URL}")
```

2020-08-26 16:42 UTC, epozine commented on vars/rpr_core_pipeline.groovy
> +                GithubNotificator.updateStatus("Test", options['stageName'], "success", env, options, "Some tests were marked as failed", "${BUILD_URL}")
```suggestion
                GithubNotificator.updateStatus("Test", options['stageName'], "success", env, options, "Some tests were marked as failed. Check the report for details.", "${BUILD_URL}")
```

2020-08-26 16:42 UTC, epozine commented on vars/rpr_core_pipeline.groovy
> +                GithubNotificator.updateStatus("Test", options['stageName'], "success", env, options, "Tests finished", "${BUILD_URL}")
```suggestion
                GithubNotificator.updateStatus("Test", options['stageName'], "success", env, options, "Tests completed successfully.", "${BUILD_URL}")
```

2020-08-26 16:42 UTC, epozine commented on vars/rpr_core_pipeline.groovy
> +            GithubNotificator.updateStatus("Test", options['stageName'], "pending", env, options, "Preparing test group", "${BUILD_URL}")
```suggestion
            GithubNotificator.updateStatus("Test", options['stageName'], "pending", env, options, "Preparing to run a test group", "${BUILD_URL}")
```

2020-08-26 16:42 UTC, epozine commented on vars/rpr_core_pipeline.groovy
> +            GithubNotificator.updateStatus("Test", options['stageName'], "pending", env, options, "Preparing test group", "${BUILD_URL}")
Возможно стоит добавить конкретное название группы

2020-08-26 16:42 UTC, epozine commented on vars/rpr_core_pipeline.groovy
> +            GithubNotificator.updateStatus("Test", options['stageName'], "pending", env, options, "Preparing test group", "${BUILD_URL}")
Еще такая идея. Может нам писать перед статус [0/12], [2/12], где 0 и 2 - текущая тестовая группа, а 12 - общее число групп? Для человека это может быть очень полезно. Я бы не отказался от такой информации и в Jenkins, но пока не знаю где лучше отображать.

2020-08-26 16:42 UTC, epozine commented on vars/rpr_core_pipeline.groovy
> +            GithubNotificator.updateStatus("Test", options['stageName'], "pending", env, options, "Preparing test group", "${BUILD_URL}")
Я думаю стоит разделить данный блок на несколько. Я выделил prepare лишь по причине, чтобы не писать 2-3 таймаута. Тут просто сгруппированы несколько быстрых вещей. 
Но если писать статус для пользователей, то лучше конкретику. Не выкачался тестовый репозиторий. Не выкачалась Core SDK.

2020-08-26 16:42 UTC, epozine commented on vars/rpr_core_pipeline.groovy
> +            String errorMessage = "Failed downloading of Assets"
```suggestion
            String errorMessage = "Failed to download test scenes"
```

2020-08-26 16:42 UTC, epozine commented on vars/rpr_core_pipeline.groovy
> +            String errorMessage = "Could not find session report"
```suggestion
            String errorMessage = "Failed to download test results. No session report found. Please contact support."
```

2020-08-26 16:42 UTC, epozine commented on vars/rpr_core_pipeline.groovy
> +                            String errorMessage = "All tests crashed"
```suggestion
                            String errorMessage = "All tests have failed. The test group will be restarted."
```

2020-08-26 16:42 UTC, epozine commented on vars/rpr_core_pipeline.groovy
> +                            String errorMessage = "All tests crashed"
Если исчерпаны попытки, то можно написать All attempts are exhausted.

2020-08-26 16:42 UTC, epozine commented on vars/rpr_core_pipeline.groovy
> +    GithubNotificator.updateStatus("Build", "Windows", "pending", env, options, "Building core", "${BUILD_URL}/artifact/Build-Windows.log")
```suggestion
    GithubNotificator.updateStatus("Build", "Windows", "pending", env, options, "Creating a RadeonProRender SDK package.", "${BUILD_URL}/artifact/Build-Windows.log")
```

2020-08-26 16:42 UTC, epozine commented on vars/rpr_core_pipeline.groovy
> +    GithubNotificator.updateStatus("Build", "Windows", "success", env, options, "Core built", "${BUILD_URL}/artifact/binWin64.zip")
```suggestion
    GithubNotificator.updateStatus("Build", "Windows", "success", env, options, "RadeonProRender SDK package successfully created.", "${BUILD_URL}/artifact/binWin64.zip")
```

2020-08-26 16:42 UTC, epozine commented on vars/rpr_core_pipeline.groovy
> +                GithubNotificator.updateStatus("Build", osName, "pending", env, options, "Clonning core repository")
```suggestion
                GithubNotificator.updateStatus("Build", osName, "pending", env, options, "Downloading RadeonProRenderSDK repository")
```

2020-08-26 16:42 UTC, epozine commented on vars/rpr_core_pipeline.groovy
> +                GithubNotificator.updateStatus("Build", osName, "pending", env, options, "Clonning core repository")
Clonning - некорректно, потому что мы не скачиваем с нуля. Могут быть вопросы.

2020-08-26 16:42 UTC, epozine commented on vars/rpr_core_pipeline.groovy
> +                GithubNotificator.updateStatus("Deploy", "Building of report", "pending", env, options, "Preparing tests", "${BUILD_URL}")
```suggestion
                GithubNotificator.updateStatus("Deploy", "Report building.", "pending", env, options, "Preparing tests", "${BUILD_URL}")
```

2020-08-26 16:42 UTC, epozine commented on vars/rpr_core_pipeline.groovy
> +                String errorMessage = "Failed report publishing"
```suggestion
                String errorMessage = "Failed to publish test report."
```

2020-08-26 16:56 UTC, MagisterDemens commented
> У меня есть несколько вопросов к данному ПРу. 
> 1. Насколько подробно мы хотим писать статус каждой стадии? Запрос был на конкретную причину, а не общую формулировку "Build was failed". Будет ли написано, что не выкачан репозиторий например? 
> 2. В коре мы не собираем плагин, возможно ли писать кастомные надписи в джобах? Мы там выкачиваем бинари же только. Звучит некорректно, что построение прошло успешно.
> 3. В максе, в случае когда упал билд, у нас успешно построен отчет. Вопрос общий, а нужно ли вообще строить какие-либо отчеты полные, если билд не собирается? Мне кажется нет. Достаточно будет причины падения билда, если упал именно код самого построения, то можно ссылку на лог приложить например. 

3. Это рабочая схема только если для всех платформ билд упал. ну и целиком пропускать деплой все равно не получится. Отчёты думаю лучше оставить, и писать там что билд упал. Так получится более понятный и привычный пользователю воркфлоу

2020-08-27 18:26 UTC, epozine approved these changes

2020-08-31 09:17 UTC, Piromancer commented
https://github.com/Speedwag00n/RadeonProRenderMayaPlugin/pull/1
continuous-integration/jenkins/pr-merge — This commit cannot be built
Что это значит? Мне не понятно, плагин ведь построился

2020-08-31 09:20 UTC, Speedwag00n commented
> 
> 
> [Speedwag00n/RadeonProRenderMayaPlugin#1](https://github.com/Speedwag00n/RadeonProRenderMayaPlugin/pull/1)
> continuous-integration/jenkins/pr-merge — This commit cannot be built
> Что это значит? Мне не понятно, плагин ведь построился

Этот статус генерируется автоматически одним из плагинов дженкинса. Его создание было выключено в тестовых джобах, будет выключено и в основных. Убедиться в этом можно по этому ПРу: https://github.com/Speedwag00n/RadeonProRenderMayaPlugin/pull/3
Лучше смотреть самые старшие ПРы, они запускались с актуальной версией ветки с гитхаб нотификациями, в предыдущих могут быть ошибки, которые уже исправлены (сейчас обновлю ссылки)

2020-08-31 09:23 UTC, Piromancer commented
https://github.com/Speedwag00n/RadeonProRenderBlenderAddon/pull/3
[DEPLOY] Building test report — Report was published successfully. Results: success - null, failed - 93, error - 0.
Null - это ожидаемо? Почему если ПР все прошел, пишет о каких-то фейлах?

2020-08-31 09:25 UTC, Speedwag00n commented
> 
> 
> [Speedwag00n/RadeonProRenderBlenderAddon#3](https://github.com/Speedwag00n/RadeonProRenderBlenderAddon/pull/3)
> [DEPLOY] Building test report — Report was published successfully. Results: success - null, failed - 93, error - 0.
> Null - это ожидаемо? Почему если ПР все прошел, пишет о каких-то фейлах?

Была опечатка в название успешно выполненных кейсов (я написал - success, а они имеются passed на самом деле). Это уже исправлено, ПР перезапускать не стал, т.к. это минорное исправление

2020-08-31 09:41 UTC, Piromancer commented
https://github.com/Speedwag00n/RadeonProRenderMaxPlugin/pull/4
[TEST] AMD_RXVEGA-Windows Pending — This stage will be executed later...
Прогон закончился, а статус не обновляется

2020-08-31 09:48 UTC, Speedwag00n commented
> 
> 
> [Speedwag00n/RadeonProRenderMaxPlugin#4](https://github.com/Speedwag00n/RadeonProRenderMaxPlugin/pull/4)
> [TEST] AMD_RXVEGA-Windows Pending — This stage will be executed later...
> Прогон закончился, а статус не обновляется

Произошел ClosedChannelException, исправления в другом ПР: https://github.com/luxteam/rpr_pipelines/pull/260

2020-08-31 09:49 UTC, Piromancer approved these changes

2020-08-31 11:42 UTC, epozine approved these changes

2020-08-31 11:52 UTC, epozine approved these changes

2020-08-31 11:52 UTC, merged