Collect and represent information about errors
luxteam/rpr_pipelines pull request #242
Opened 2020-08-19 14:53 UTC by Speedwag00n

### Jira Ticket
* https://adc.luxoft.com/jira/browse/STVCIS-1264
### Purpose
* Make reports and build page more informative by representing of information about errors
### Effect of change
* Add information about errors in build description and in information about retries
* Fix collecting of retries info when there are more than one retry for one test group or there are more than one retry for platform.
### Technical steps
- [x] ProblemMessageManager allows to save and clear error messages for different stages or OS. See its implementation for more info (it contains documentation)
- [x] There is 3 types of error messages: Specific which represent some specific error, General which are used when any specific error can't be determinated and Global which isn't related with any stage or OS and describe whole build.
- [x] After build in finally block function for publish errors is calling.
### :octocat: Related PR'S
* jobs_launcher: https://github.com/luxteam/jobs_launcher/pull/70
* jobs_test_blender: https://github.com/luxteam/jobs_test_blender/pull/101
* jobs_test_maya: https://github.com/luxteam/jobs_test_maya/pull/153
* jobs_test_max: https://github.com/luxteam/jobs_test_max/pull/40
* jobs_test_core: https://github.com/luxteam/jobs_test_core/pull/22
* jobs_test_rprviewer: https://github.com/luxteam/jobs_test_rprviewer/pull/35
### Jenkins Builds
* See related PRs

2020-08-20 16:03 UTC, Kataderon commented on vars/isTimeoutExceeded.groovy
> +def call(Exception e) {
Почему нельзя поместить в utils?

2020-08-20 16:04 UTC, Kataderon commented on vars/multiplatform_pipeline.groovy
> +import java.text.SimpleDateFormat
Такие изменения лучше мерджить отдельно в pr на код стайл

2020-08-20 16:09 UTC, Kataderon commented on vars/multiplatform_pipeline.groovy
> +                                    options['nodeRetry'].add([Testers: nodesList, gpuName: asicName, osName: osName, Tries: [[(testsOrTestPackage): [[host:env.NODE_NAME, link:"${testsOrTestPackage}.$
Думаю, лучше вынести общую часть из этой и 95 строки, чтобы сократить их для читабельности

2020-08-20 16:16 UTC, Kataderon requested changes
В целом хорошо, нужно будет пересмотреть после тестирования в дженкинсе

2020-08-20 16:30 UTC, Speedwag00n commented on vars/isTimeoutExceeded.groovy
> +def call(Exception e) {
Добавил этот метод до того, как класс utils был имплементирован. Переработаю

2020-08-25 15:23 UTC, Piromancer approved these changes

2020-08-26 11:39 UTC, MagisterDemens reviewed
1. Офф. документация говорит создавать классы в src каталоге. Наверняка не уверен, но кажется в этом случае автоматически контекст подтягивается.
2. Для массивных изменений в multiplatfrom - прогонов на плагины недостаточно. Надо проверить что с рифом/гибридом, пайплайны в которых не используется новая фича, но используется mulitplatform
Ждем: https://rpr.cis.luxoft.com/view/RPR-Baikal/job/RadeonProRender-HybridManual/463/
Но на всякий случай, проверь и сам.

2020-08-26 12:09 UTC, Speedwag00n commented
ML: https://rpr.cis.luxoft.com/view/RadeonML/job/RadeonML_Manual/50/console
RIF: https://rpr.cis.luxoft.com/job/RadeonProImageProcessingManual/661/console

2020-08-26 13:42 UTC, MagisterDemens approved these changes

2020-08-26 14:54 UTC, epozine approved these changes

2020-08-26 14:56 UTC, merged