Store baselines on testers
luxteam/rpr_pipelines pull request #251
Opened 2020-08-24 11:58 UTC by Kataderon

### Jira Ticket
https://adc.luxoft.com/jira/browse/STVCIS-1417

### Effect of change
Increase performance of autotests

### Jenkins Builds
https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/RadeonProRenderBlender2.8PluginManual/2483/

2020-08-24 14:11 UTC, epozine commented on vars/rpr_blender28plugin_pipeline.groovy
>                  options.tests.split(" ").each() {
Как ты считаешь, может лучше данный функционал перенести в simpleRender? Тебе нужно будет добавить гибкое копирование regression, а из simpleRender это делать будет удобнее возможно.

2020-08-24 15:07 UTC, Piromancer requested changes
https://rpr.cis.luxoft.com/view/RPR-Baikal/job/RadeonProViewerManual/748/Test_20Report/
Не подгрузились бейзлайны на убунте

2020-08-24 15:13 UTC, Piromancer requested changes

2020-08-24 15:13 UTC, Piromancer commented on vars/rpr_blender28plugin_pipeline.groovy
> +                String middle_dir = isUnix() ? "${CIS_TOOLS}/../TestResources/rpr_blender_autotests_baselines" : "/mnt/c/TestResources/rpr_blender_autotests_baselines"
Мне все таки кажется проблема в этой строчке

2020-08-24 15:14 UTC, Kataderon commented on vars/rpr_blender28plugin_pipeline.groovy
> +                String middle_dir = isUnix() ? "${CIS_TOOLS}/../TestResources/rpr_blender_autotests_baselines" : "/mnt/c/TestResources/rpr_blender_autotests_baselines"
Аргументировать можешь?

2020-08-25 08:08 UTC, Piromancer commented
https://rpr.cis.luxoft.com/job/RadeonProRenderCoreManual/682/Test_20Report/
Вот еще билд, где не прогрузились бейзлайны

2020-08-25 09:45 UTC, closed without merging