Add retires option
luxteam/rpr_pipelines pull request #281
Opened 2020-09-07 14:06 UTC by Kataderon

## JIRA TICKET
https://adc.luxoft.com/jira/browse/STVCIS-1500
https://adc.luxoft.com/jira/browse/STVCIS-1490

##PURPOSE
Add retries option for viewer, blender and maya

## RELATED PR'S
https://github.com/luxteam/jobs_test_maya/pull/165
https://github.com/luxteam/jobs_test_blender/pull/113
https://github.com/luxteam/jobs_test_rprviewer/pull/38

## REPORTS

2020-09-10 10:02 UTC, Piromancer requested changes
Нет отчетов

2020-09-17 20:40 UTC, epozine approved these changes
Ждем мержа Пра вьера на ретраи

2020-09-22 17:55 UTC, epozine submitted a review, later dismissed

2020-09-25 08:25 UTC, epozine approved these changes

2020-09-25 08:30 UTC, merged