STVCIS-1581 (Display build parameters)
luxteam/rpr_pipelines pull request #359
Opened 2020-11-04 16:53 UTC by dm1tryG

### Jira Ticket
https://adc.luxoft.com/jira/browse/STVCIS-1581

### PurposeS

Send parameters on createBuild stage

### Effect of change

* Changed createBuild() method
* Added static fields for send from each tool
* Added conversion parameters stage for each tool

### :octocat: Related PR'S
https://github.com/luxteam/rpr_pipelines/pull/355

### Jenkins Builds
Blender [done]:
https://ums2.cistest.luxoft.com/products/5f881e5a8e8872f31dc413e0/5fa2bc19253e2e7072996511
Maya [done]:
https://ums2.cistest.luxoft.com/products/5f881e5a8e8872f31dc413e3/5fa2d2ee253e2e7072996614
Core [done]:
https://ums2.cistest.luxoft.com/products/5f881e5a8e8872f31dc413ec/5fa2d558253e2e7072996688
Max [done]:
https://ums2.cistest.luxoft.com/products/5f881e5a8e8872f31dc413e6/5fa2d2b2253e2e7072996605
Viewer [done]:
https://ums2.cistest.luxoft.com/products/5f881e5a8e8872f31dc413e9/5fa2d31a253e2e7072996621

2020-11-05 06:48 UTC, Speedwag00n commented
Может быть стоит вынести список полей в одну большую мапу в UniverseClient и также добавить в UniverseClient функцию для сбора нужных полей из options, а не делать это в пайплайне?
@epozine, что думаешь?

2020-11-05 06:49 UTC, Speedwag00n commented on vars/UniverseClient.groovy
> +    def createBuild(envs = '', suites = '', updRefs = false, parameters = [:], info = [:]) {
Тут тоже может быть полезно описание параметров parameters и info

2020-11-19 09:48 UTC, epozine requested changes

2020-11-19 09:48 UTC, epozine commented on vars/rpr_blender28plugin_pipeline.groovy
> +@Field Map[] UMSMajorPrarmetersKeys = [
Зачем мы второй раз описыванием те же переменные, что и в самом пайпайне? И зачем это в пайплайне блендера?

2020-11-19 09:48 UTC, epozine commented
Убери пожалуйста изменения Ильи, которые уже в мастере. Они мешают ревью, а также реши конфликты

2020-11-23 13:34 UTC, Speedwag00n submitted a review, later dismissed

2020-11-23 14:48 UTC, epozine approved these changes

2020-11-23 14:52 UTC, merged