Akulbako/matlib checking
luxteam/rpr_pipelines pull request #405
Opened 2020-12-16 16:18 UTC by testpassword

### Jira Ticket
- https://adc.luxoft.com/jira/secure/RapidBoard.jspa?rapidView=1577&projectKey=STVCIS&view=planning&selectedIssue=STVCIS-1979

### Purpose
- Checking whether the material library has been installed on a node

### Effect of change
- Checks the presence of the material on the scene, if it is absent, installs the library. Checks the fact of installation through the registry on windows systems.

### Technical steps
- [x] Creates test scene with link to material from AMD library
- [x] Call matlib script
- [x] Check registry key on Windows

### :octocat: Related PR'S
- https://github.com/luxteam/jobs_test_maya/pull/260
- https://github.com/luxteam/jobs_test_blender/pull/181

### Jenkins Builds
- https://rpr.cis.luxoft.com/job/DevRadeonProRenderBlender2.8PluginManual/671/
- https://rpr.cis.luxoft.com/job/DevRadeonProRenderMayaPluginManual/89/

2020-12-18 10:16 UTC, epozine commented on vars/rpr_blender28plugin_pipeline.groovy
> +                                    else throw new ExpectedExceptionWrapper("Can't verify matlib installation.")
Нужен вызов функции установки матлибы в случае ее отсутствия

2020-12-18 10:18 UTC, epozine commented on vars/rpr_blender28plugin_pipeline.groovy
> +                            if (compareRC == 1) {
Мне кажется использовать такой пород не стоит, потому что в случае изменений каких-то в плагине может быть фейл даже в случае наличия матлибы. Может пробрасывать порог еще более низкий?

2020-12-20 15:27 UTC, testpassword commented on vars/rpr_blender28plugin_pipeline.groovy
> +                                    else throw new ExpectedExceptionWrapper("Can't verify matlib installation.")
Установка чуть выше (https://github.com/luxteam/rpr_pipelines/blob/akulbako/matlib-checking/vars/rpr_blender28plugin_pipeline.groovy#L353), после сравнения изображения, если они не совпадают, а строки 354-357 - это уже проверка факта установки.  Можно после неудачной проверки реестра вызвать установку ещё раз, но тогда ещё раз и проверять. Получается, делать это нужно в цикле пока реестр не вернёт положительный результат?

2020-12-20 15:30 UTC, testpassword commented on vars/rpr_blender28plugin_pipeline.groovy
> +                            if (compareRC == 1) {
Не понял, про что идёт речь. Опиши пожалуйста подробнее.

2020-12-30 09:13 UTC, epozine requested changes

2020-12-30 09:21 UTC, Speedwag00n commented on vars/rpr_blender28plugin_pipeline.groovy
> +                println "[ERROR] Failed checking matlib installation ${e.toString()}"
Принт не во всех случаях верно описывает ситуацию. Можно оставить так, сейчас это все равно переписывается

2020-12-30 09:23 UTC, Speedwag00n requested changes
Согласен с замечаниями Андрея. Советы по код стайлу скину в ближайшее время

2020-12-30 09:36 UTC, testpassword commented on vars/installMatlib.groovy
> +            // unfortunately msiexec doesn't work with relative paths (.. and . as a part of path return error too)
Убрал лишнее

2020-12-30 09:41 UTC, testpassword commented on vars/installMatlib.groovy
> +            println "Not supported yet"
Забыл, сейчас всё supported)

2020-12-30 09:47 UTC, testpassword commented on vars/receiveFiles.groovy
> +            %CIS_TOOLS%\\receiveFiles.bat ${remote.replace("\\", "/")} ${local.replace("\\", "/")}
Мне кажется, это далеко не очевидно для того, кто вызывает recieveFiles, лично я б это споткнулся. Особенно учитавая тот факт, что сам bash выдаёт в качестве ошибки неочивидную фразу "Unexpected end of file", что сбивает с толку, ибо начинаешь проверять файл на наличие crlf символов, скрытых символом возврата каретки, но никак не на слэши. Не лучше ли перестраховаться и оставить здесь замену виндовых слешей на униксовые?

2020-12-30 09:56 UTC, testpassword commented on vars/rpr_blender28plugin_pipeline.groovy
> +                    timeout(time: "16", unit: 'MINUTES') {
Матлиба бывает достаточно долго устанавливается и удаляется (были случаи по 3+ минуты на операцию). Сократил до 12 мин, но ещё больше сокращать рискованно

2020-12-30 09:59 UTC, testpassword commented on vars/rpr_blender28plugin_pipeline.groovy
> +                println "[ERROR] Failed checking matlib installation ${e.toString()}"
Это да, заглушка. Просто в той реализации что была, вообще никакой инфы по исключению не было

2020-12-30 10:14 UTC, testpassword commented on vars/verifyMatlib.groovy
> +            case "OSX":
Ок

2020-12-30 10:26 UTC, testpassword commented on vars/installMatlib.groovy
> +            String installerPath = "C:\\JN\\TestResources\\RadeonProMaterialLibrary.msi"
+

2020-12-30 10:28 UTC, testpassword commented on vars/rpr_blender28plugin_pipeline.groovy
> +                        } else verifyMatlib("Blender", cacheImgPath, osName, options)
Добавить тут и для Blender, Maya или один раз в verifyMatlib?

2020-12-30 10:34 UTC, testpassword commented on vars/verifyMatlib.groovy
> +    Integer allowableDiff // 76% percent - the difference between a picture with matlib and without for blender and 53% for maya
Сделал

2020-12-30 10:35 UTC, epozine commented on vars/rpr_blender28plugin_pipeline.groovy
> +                        } else verifyMatlib("Blender", cacheImgPath, osName, options)
Код стайл глянь, пункт 15

2020-12-30 10:44 UTC, testpassword commented on vars/installMatlib.groovy
> +                echo "RadeonProMaterialLibrary installed"
Да, убрал

2021-01-11 17:08 UTC, epozine requested changes

2021-01-11 17:08 UTC, epozine commented on vars/installMatlib.groovy
> +                downloadMatlib("https://rpr.cis.luxoft.com/job/RadeonProRenderMaterialLibrary/12/artifact/RadeonProRenderMaterialLibrary.msi", "C:\\TestResources\\")
1. Нужно спрятать URL в креды (он там уже есть скорее всего, домен люксофта не нужно наружу выставлять)
2. Вместо downloadMatlib сделай функцию downloadFile. Зачем нам привязываться к матлибе? Просто скачивание по ссылке

2021-01-12 13:52 UTC, Speedwag00n requested changes

2021-01-12 13:52 UTC, Speedwag00n commented on vars/downloadFile.groovy
> +    command += "${filelink} "
Формирование команды в одну строку, хоть и избычно, зато нагляднее
```suggestion
    String command
    if (credentialsId) {
        withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: credentialsId, usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
            command = "curl -L -o ${outputDir}${filename} -u ${USERNAME}:${PASSWORD} ${filelink}"
        }
    } else {
        command = "curl -L -o ${outputDir}${filename} ${filelink}"
    }
```

2021-01-12 13:52 UTC, Speedwag00n commented on vars/downloadFile.groovy
> +    if (isUnix()) sh command else bat command
```suggestion
    if (isUnix()) {
        sh command 
    } else {
        bat command
    }
```

2021-01-12 13:52 UTC, Speedwag00n commented on vars/downloadFile.groovy
> +def call(String filelink, String outputDir = "./", String credentialsId = "") {
В целом эта функция небольшая и достаточно общая, ее можно вынести в utils.groovy

2021-01-12 13:52 UTC, Speedwag00n commented on vars/installMatlib.groovy
> +    String installMsg = "[INFO] Installing Material Library..."
Сообщения в логах используются только на нашей стороне. Выносить их в отдельные переменные будет только мешать читать код. Особенно это актуально в больших файлах, где искать нужную переменную с разбросом в сотни строк будет неприятно

2021-01-12 13:52 UTC, Speedwag00n commented on vars/installMatlib.groovy
> +                            JENKINS_URL + "/job/RadeonProRenderMaterialLibrary/lastSuccessfulBuild/artifact/RadeonProRenderMaterialLibrary.msi",
```suggestion
                            "${JENKINS_URL}/job/RadeonProRenderMaterialLibrary/lastSuccessfulBuild/artifact/RadeonProRenderMaterialLibrary.msi",
```

2021-01-12 13:52 UTC, Speedwag00n commented on vars/installMatlib.groovy
> +                            JENKINS_URL + "/job/RadeonProRenderMaterialLibrary/lastSuccessfulBuild/artifact/RadeonProRenderMaterialLibrary.run",
```suggestion
                            "${JENKINS_URL}/job/RadeonProRenderMaterialLibrary/lastSuccessfulBuild/artifact/RadeonProRenderMaterialLibrary.run",
```

2021-01-12 13:52 UTC, Speedwag00n commented on vars/installMatlib.groovy
> +                echo ${installMsg}
```suggestion
                println "${installMsg}"
```

2021-01-12 13:52 UTC, Speedwag00n commented on vars/verifyMatlib.groovy
> +    } else println "[INFO] build_cache and baseline image are equal: matlib already installed on this node."
```suggestion
    } else {
        println "[INFO] build_cache and baseline image are equal: matlib already installed on this node."
    }
```

2021-01-12 13:52 UTC, Speedwag00n commented on vars/rpr_blender28plugin_pipeline.groovy
> +                println "[ERROR] Failed checking matlib installation ${e.toString()}"
Это сообщение может быть выведено, если будет завалена установка плагина или генерация картинки. Тогда это сообщение может запутать при прочтении лога. Можно его пока убрать, почти готов рефактор сбора сообщений об важных ошибках, сразу можно будет использовать переработанный вариант

2021-01-12 13:52 UTC, Speedwag00n commented on vars/rpr_mayaplugin_pipeline.groovy
> +                    println "[ERROR] Failed checking matlib installation ${e.toString()}"
Это сообщение может быть выведено, если будет завалена установка плагина или генерация картинки. Тогда это сообщение может запутать при прочтении лога. Можно его пока убрать, почти готов рефактор сбора сообщений об важных ошибках, сразу можно будет использовать переработанный вариант

2021-01-12 13:52 UTC, Speedwag00n commented on vars/verifyMatlib.groovy
> +        String fail = "[INFO] Can't verify matlib installation"
Как уже писал выше, скорее лишний раз отвлекает при чтении кода, чем делает его чище

2021-01-12 13:52 UTC, Speedwag00n commented on vars/verifyMatlib.groovy
> +    Double compareRC = parsePythonStdout(python3("./jobs_launcher/common/scripts/CompareMetrics.py --img1 ${cacheImgPath} --img2 ${baselineImgPath}"))
Лучше вынести эту логику в utils, в некоторых других пайплайнах эта функция также пригодится. Так чуть больше кода, зато читается проще
```suggestion
    println "[INFO] Comparing material baseline and created image"
    def compareRCRaw = python3("./jobs_launcher/common/scripts/CompareMetrics.py --img1 ${cacheImgPath} --img2 ${baselineImgPath}")
    def compareRC
    if (isUnix()) {
        compareRC = compareRCRaw
    } else {
        compareRC = compareRCRaw.split(" ").last()
    }
```

2021-01-12 13:52 UTC, Speedwag00n commented on vars/verifyMatlib.groovy
> +                Integer regRC = parsePythonStdout(python3("./jobs_launcher/common/scripts/check_matlib_registry.py --tool ${tool}")) as Integer
Написал выше, что стоит вынести в utils

2021-01-12 13:52 UTC, Speedwag00n commented on vars/verifyMatlib.groovy
> +                else throw new ExpectedExceptionWrapper(fail)
```suggestion
                if (regRC == 0) {
                    println success
                } else {
                    throw new ExpectedExceptionWrapper(fail)
                }
```

2021-01-12 18:19 UTC, testpassword commented on vars/verifyMatlib.groovy
> +        String fail = "[INFO] Can't verify matlib installation"
Они несколько раз используется (success 2 раза, fail 3 раза), тем более объявлены максимально близко от места вызова, чтобы не терять

2021-01-12 18:21 UTC, testpassword commented on vars/downloadFile.groovy
> +    command += "${filelink} "
Это сделано на случай, если понадобится дополнительные параметры прикрутить к строке (что-то типо билдера команды)

2021-01-13 05:57 UTC, Speedwag00n commented on vars/downloadFile.groovy
> +    command += "${filelink} "
Уверен, что новые параметры не понадобятся. Не могу даже представить себе такой кейс в данном случае

2021-01-13 10:54 UTC, epozine reviewed
Обнови отчеты и все ок

2021-01-13 10:54 UTC, epozine commented on vars/installMatlib.groovy
> +                            "jenkinsUser")
Скобку можно перенести для лучшей читаемости. Минор.

2021-01-13 10:54 UTC, epozine commented on vars/utils.groovy
> +            extraParams.each { command += "-${it.key} ${it.value} " }
Какие дополнительные параметры ты хочешь использовать?

2021-01-13 10:54 UTC, epozine commented on vars/utils.groovy
> +                command += "-u ${USERNAME}:${PASSWORD} "
Опять же если не будет дополнительных параметров, то возможно проще формировать строку один раз полностью.

2021-01-13 10:54 UTC, epozine commented on vars/verifyMatlib.groovy
> +            baselineImgPath += "maya_material_baseline.jpg"
Не забудь вернуть обратно

2021-01-13 10:54 UTC, epozine commented on vars/verifyMatlib.groovy
> +        String fail = "[INFO] Can't verify matlib installation"
```suggestion
        String failure = "[INFO] Can't verify matlib installation"
```

2021-01-13 10:54 UTC, epozine commented on vars/verifyMatlib.groovy
> +                    println success
Зачем переменная? Проще сразу строку вписать

2021-01-13 10:54 UTC, epozine commented on vars/verifyMatlib.groovy
> +                println fail
Скорее not supported, чем fail

2021-01-13 10:54 UTC, epozine commented on vars/verifyMatlib.groovy
> +                    println success
Возможно сможем использовать потом код Ильи, где данные сообщение все будут.

2021-01-13 11:12 UTC, testpassword commented on vars/verifyMatlib.groovy
> +                    println success
Думал, что сильно длинная. Убрал

2021-01-13 11:29 UTC, testpassword commented on vars/utils.groovy
> +            extraParams.each { command += "-${it.key} ${it.value} " }
Вполне себе может понадобится когда-нибудь параметр -F для отправки формы запроса и --data для передачи параметров в url, -X если вдруг get запроса будет недостаточно

2021-01-14 09:04 UTC, epozine submitted a review, later dismissed

2021-01-14 09:15 UTC, Speedwag00n submitted a review, later dismissed

2021-01-14 09:29 UTC, merged