Simplify adding of notifications to Jenkins pipelines
luxteam/rpr_pipelines pull request #418
Opened 2020-12-31 12:36 UTC by Speedwag00n

### Jira Ticket
* https://adc.luxoft.com/jira/browse/STVCIS-1538
### Purpose
* Simplify adding of notifications to Jenkins pipelines
### Effect of change
* Impelement withNotifications structure for wrap block of code for which some configured notifications should be used.
* Impelement file with configuration of notifications which can be called before execution of code, after successful execution of code or in case of some exception.
* Replace notifications by withNotifications structure where it is possible.
### Technical steps
- [x] New classes and some existing classes move to "src" dir
- [x] Messages for Notifications should be configured in NotificationConfiguration class as static fields
- [x] For more information about usage of withNotifications block see documentation in withNotifications.groovy script
### :warning: Notes for Reviewers
* THESE CHANGES AREN'T TESTED ENOUGH. WORK IN PROGRESS
### Jenkins Builds
* Coming soon

2021-01-11 17:03 UTC, epozine commented on src/NotificationConfiguration.groovy
> +    def static BUILD_PLUGIN = [
BUILD_SOURCE_CODE?

2021-01-11 17:03 UTC, epozine commented on src/NotificationConfiguration.groovy
> +                "class": Exception, "problemMessage": "Failed to build the plugin.",
```suggestion
                "class": Exception, "problemMessage": "Failed to build the package(?).", 
```

2021-01-11 17:03 UTC, epozine commented on src/NotificationConfiguration.groovy
> +    def static BUILD_PLUGIN = [
Если сильно хочется конкретики, то может просто название Тулы прокидывать?

2021-01-12 06:58 UTC, Speedwag00n commented on src/NotificationConfiguration.groovy
> +    def static BUILD_PLUGIN = [
Заменю названия тулов в сообщениях на более общие. Это должно быть понятно из названия джобы/репо, не подумал про это сразу
И так слишком много опциональных параметров получилось, можно запутаться.

2021-01-12 09:44 UTC, Piromancer approved these changes

2021-01-12 11:51 UTC, Speedwag00n commented on src/NotificationConfiguration.groovy
> +    def static BUILD_PLUGIN = [
Изменения внес и протестировал

2021-01-13 11:41 UTC, epozine requested changes

2021-01-13 11:41 UTC, epozine commented on src/NotificationConfiguration.groovy
> +    def static BUILD_SOURCE_CODE_MESSAGE = "Building the project."
```suggestion
    def static BUILD_SOURCE_CODE_START_MESSAGE = "Building the project."
```

2021-01-13 11:41 UTC, epozine commented on src/NotificationConfiguration.groovy
> +    def static SOURCE_CODE_BUILT = "The project was successfully built and published."
```suggestion
    def static BUILD_SOURCE_CODE_END_MESSAGE = "The project was successfully built and published."
```

2021-01-13 11:41 UTC, epozine commented on src/NotificationConfiguration.groovy
> +    def static SOURCE_CODE_BUILT = "The project was successfully built and published."
Мне не очень нравится, что у тебя старт и конец абсолютно разные фразы. Мне кажется в моем варианте будет проще жить. Можно подумать над формулировкой.

2021-01-13 11:41 UTC, epozine commented on vars/rpr_core_internal_pipeline.groovy
> +    withNotifications(title: "WIndows", options: options, beginUrl: "${BUILD_URL}/artifact/Build-Windows.log",
```suggestion
    withNotifications(title: "Windows", options: options, beginUrl: "${BUILD_URL}/artifact/Build-Windows.log",
```

2021-01-13 11:41 UTC, epozine commented on vars/rpr_core_internal_pipeline.groovy
> +                    if (universeClientProd.build != null || universeClientDev != null){
```suggestion
                    if (universeClientProd.build != null || universeClientDev.build != null){
```

2021-01-13 11:41 UTC, epozine commented on vars/withNotifications.groovy
> + *     beginUrl (optional) - Url which will be set in status check before execution of code
```suggestion
 *     logUrl (optional) - Url which will be set in status check before execution of code
```

2021-01-13 11:41 UTC, epozine commented on vars/withNotifications.groovy
> + *     endUrl (optional) - Url which will be set in status check if code was finished without exceptions
```suggestion
 *      artifactUrl (optional) - Url which will be set in status check if code was finished without exceptions
```

2021-01-13 11:47 UTC, Speedwag00n commented on src/NotificationConfiguration.groovy
> +    def static DOWNLOAD_USD_REPO = [
Эти же сообщения будут высвечитьваться в описании билда, если возникнет ошибка. Нам будет быстрее понять, на каком моменте упал билд

2021-01-13 11:47 UTC, Speedwag00n commented on src/NotificationConfiguration.groovy
> +    def static DOWNLOAD_JOBS_LAUNCHER = [
DOWNLOAD_JOBS_LAUNCHER отображается только в логах, в Github нотификациях и сообщениях об ошибках его не будет

2021-01-13 13:35 UTC, epozine approved these changes

2021-01-13 13:56 UTC, merged