Implement deleting of report after its successfully publishing
luxteam/rpr_pipelines pull request #439
Opened 2021-01-22 16:53 UTC by Speedwag00n

### Jira Ticket
* https://adc.luxoft.com/jira/browse/STVCIS-2039
### Purpose
* Implement deleting of report after its successfully publishing
### Jenkins Builds
* https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/3603/

2021-01-22 18:38 UTC, epozine requested changes
Может лучше воркспейс очищать?

2021-01-22 18:38 UTC, epozine commented on vars/utils.groovy
> +            removeDir(self, "Windows", reportDir)
```suggestion
            cleanWS()
```

2021-01-24 13:31 UTC, Speedwag00n commented on vars/utils.groovy
> +            removeDir(self, "Windows", reportDir)
Согласен, очищать воркспейс будет эффективнее (так точно ничего не забудем).
Единственное, перенес его вызов сразу после исполнения всей deploy стадии (после публикации отчета очищать директорию нельзя, т.к. данные из нее все еще будут нужны)

2021-01-24 13:39 UTC, epozine approved these changes

2021-01-24 13:39 UTC, merged