Add fixed end time ums
luxteam/rpr_pipelines pull request #442
Opened 2021-01-25 23:16 UTC by GulDilin

### Jira Ticket
https://adc.luxoft.com/jira/browse/STVCIS-2029

### Purpose
Set status time from pipelines to make timestamp for parent build and children builds same

### Effect of change
Timestamp from pipelines

### Technical steps
- [x] import Date
- [x] add timestamp to request

### Jenkins Builds
- https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/3628/

![изображение](https://user-images.githubusercontent.com/44547381/105777916-54e7e880-5f7c-11eb-984b-17ab5d9f7a06.png)

2021-01-26 07:59 UTC, epozine requested changes

2021-01-26 07:59 UTC, epozine commented on vars/rpr_blender28plugin_pipeline.groovy
> +                        UniverseURLDev = "https://umsapi3.cistest.luxoft.com/"
Не используй домены в открытом виде пожалуйста

2021-01-26 09:58 UTC, GulDilin commented on vars/rpr_blender28plugin_pipeline.groovy
> +                        UniverseURLDev = "https://umsapi3.cistest.luxoft.com/"
Извиняюсь, убрал

2021-01-27 17:40 UTC, Speedwag00n approved these changes

2021-01-29 11:46 UTC, epozine approved these changes

2021-01-29 11:46 UTC, merged