Akulbako/houdini ums integration
luxteam/rpr_pipelines pull request #465
Opened 2021-02-06 14:33 UTC by testpassword

### Jira Ticket
- https://adc.luxoft.com/jira/browse/STVCIS-1996

### Purpose
- Integrate Houdini and USDPlugin for AMD Radeon ProRender

### Effect of change
- USDPlugin builds now shows in UMS prod and dev

### Jenkins Builds
- https://rpr.cis.luxoft.com/job/DevJobs/job/DevRadeonProRenderUSDPlugin_with_UMS/66/
- https://ums.stvcis.luxoft.com/products/601ad187746b2a28feb82684/601e922a746b2a28febad4b0/summary
- https://ums.cistest.luxoft.com/products/601acc49b9ec98503660224c/601e922bd0d5d8ec4a2096f8/summary

2021-02-08 16:36 UTC, Speedwag00n requested changes
В добавку к комментариям по коду:
В самом билде в UMS не работает ссылка на Jenkins билд
При открытии списка артефактов возникает ошибка

2021-02-08 16:36 UTC, Speedwag00n commented on vars/rpr_usdplugin_pipeline.groovy
> +            String buildName = "RadeonProRenderUSDPlugin_${options.pluginVersion}${options.branch_postfix ? ".${options.branch_postfix}" : ""}.zip"
Так меньше глаза цепляются за внутренние кавычки
```suggestion
            String buildName = """RadeonProRenderUSDPlugin_${options.pluginVersion}${options.branch_postfix ? ".${options.branch_postfix}" : ""}.zip"""
```

2021-02-08 16:36 UTC, Speedwag00n commented on vars/rpr_usdplugin_pipeline.groovy
> +            String buildName = "RadeonProRenderUSDPlugin_${options.pluginVersion}${options.branch_postfix ? ".${options.branch_postfix}" : ""}.zip"
```suggestion
            String buildName = """RadeonProRenderUSDPlugin_${options.pluginVersion}${options.branch_postfix ? ".${options.branch_postfix}" : ""}.zip"""
```

2021-02-08 16:36 UTC, Speedwag00n commented on vars/rpr_usdplugin_pipeline.groovy
> +    def batExt = { bat(script: it, returnStdout: true).split('\r\n')[2].trim() }
Если добавить @ перед коммандой, то bat не будет добавлять в начало stdout введенную команду. Можно тогда не сплитить, а сразу использовать весь возвращаемый stdout + вызвать trim на всякий случай
Будет еще здорово вынести эту функцию в utils, т.к. она может быть использована во многих пайплайнах. Только нужно придумать ей более дескриптивное название. Может быть getBatOutput?

2021-02-08 16:36 UTC, Speedwag00n commented on vars/rpr_usdplugin_pipeline.groovy
> +                    options.universeManager.sendToMINIO(options, "Windows", "..\\RadeonProRenderUSD\\build", buildName, false)
Во всех функциях execute<osName>Build в параметре osName передается Winodws. Можно передать значение переменной, чтобы не запутаться
```suggestion
                    options.universeManager.sendToMINIO(options, osName, "..\\RadeonProRenderUSD\\build", buildName, false)
```

2021-02-08 16:36 UTC, Speedwag00n commented on vars/rpr_usdplugin_pipeline.groovy
> +                    options.universeManager.sendToMINIO(options, "Windows", "../RadeonProRenderUSD/build", buildName, false)
```suggestion
                    options.universeManager.sendToMINIO(options, osName, "../RadeonProRenderUSD/build", buildName, false)
```

2021-02-08 16:36 UTC, Speedwag00n commented on vars/rpr_usdplugin_pipeline.groovy
> +                    options.universeManager.sendToMINIO(options, "Windows", "../RadeonProRenderUSD/build", buildName, false)
```suggestion
                    options.universeManager.sendToMINIO(options, osName, "../RadeonProRenderUSD/build", buildName, false)
```

2021-02-08 16:36 UTC, Speedwag00n commented on vars/rpr_usdplugin_pipeline.groovy
> +                    options.universeManager.sendToMINIO(options, osName, "../${env.STAGE_NAME}_RIF_Trace/**", "*.*")
Скрипт в данный момент не работает с множественными путями. Заведу тикет на такую фичу, чтобы не забыть

2021-02-08 16:49 UTC, testpassword commented on src/universe/UniverseClient.groovy
> -                'ts': timestamp
Видимо при merge ошибся я

2021-02-08 16:55 UTC, Speedwag00n commented on vars/rpr_usdplugin_pipeline.groovy
> +                    options.universeManager.sendToMINIO(options, osName, "../${env.STAGE_NAME}_RIF_Trace/**", "*.*")
https://adc.luxoft.com/jira/browse/STVCIS-2087

2021-02-08 17:24 UTC, testpassword commented on vars/rpr_usdplugin_pipeline.groovy
> +                    options.universeManager.sendToMINIO(options, osName, "../${env.STAGE_NAME}_RIF_Trace/**", "*.*")
Не понял, нужно ли мне с этим что-то делать сейчас?

2021-02-08 17:28 UTC, Speedwag00n commented on vars/rpr_usdplugin_pipeline.groovy
> +                    options.universeManager.sendToMINIO(options, osName, "../${env.STAGE_NAME}_RIF_Trace/**", "*.*")
Нет, в этом ПРе ничего менять не надо касательно этого. Просто к сведению, что пока такой вызов не работает

2021-02-08 20:06 UTC, testpassword commented
> 
> 
> В добавку к комментариям по коду:
> В самом билде в UMS не работает ссылка на Jenkins билд
> При открытии списка артефактов возникает ошибка

Видимо это из-за переноса джобы в группу DevJobs url-ы сломались. Протестирую вне неё.

2021-02-08 20:16 UTC, testpassword commented on vars/rpr_usdplugin_pipeline.groovy
> +    def batExt = { bat(script: it, returnStdout: true).split('\r\n')[2].trim() }
![изображение](https://user-images.githubusercontent.com/48172248/107275929-6c869d00-6a63-11eb-8c51-eeb9dd872295.png)
Не понял как сделать(

2021-02-08 20:55 UTC, GulDilin requested changes

2021-02-08 20:55 UTC, GulDilin commented on src/universe/UniverseClient.groovy
> -import java.util.Date;
Зачем было сделано это изменение? Из-за него ведь не будет работать код в методе changeStatus, который выставляет timestamp для статуса

2021-02-08 21:41 UTC, testpassword commented on src/universe/UniverseClient.groovy
> -import java.util.Date;
ошибка мёржда

2021-02-10 06:20 UTC, Speedwag00n requested changes
Не отправляются логи для каждого кейса в отдельности. Нужно еще будет убедиться, что после отправки они будут доступны на фронте

2021-02-10 06:20 UTC, Speedwag00n commented on vars/rpr_usdplugin_pipeline.groovy
> +        options['buildName'] = """"RadeonProRenderUSDPlugin_${options.pluginVersion}${options.branch_postfix ? ".${options.branch_postfix}" : ""}.zip"""
Архивы с плагином называются по другому и в целом имеют другое расширение:
https://rpr.cis.luxoft.com/job/DevRadeonProRenderUSDPlugin_with_UMS/75/artifact/
hdRpr-2.0.22-Houdini-18.5.351-py2.7-macOS.tar.gz
hdRpr-2.0.22-Houdini-18.5.351-py2.7-ubuntu18.04.tar.gz
hdRpr-2.0.22-Houdini-18.5.351-py2.7-Windows.tar.gz

2021-02-10 06:20 UTC, Speedwag00n commented on vars/rpr_usdplugin_pipeline.groovy
> +                """
```suggestion
                println """
                     [ERROR] CAN'T GET TESTS STATUS
                     ${e.toString()}
                """
```

2021-02-10 10:45 UTC, testpassword commented on vars/rpr_usdplugin_pipeline.groovy
> +        options['buildName'] = """"RadeonProRenderUSDPlugin_${options.pluginVersion}${options.branch_postfix ? ".${options.branch_postfix}" : ""}.zip"""
Не заметил, спс

2021-02-12 12:25 UTC, Speedwag00n submitted a review, later dismissed

2021-02-14 20:17 UTC, GulDilin submitted a review, later dismissed

2021-02-18 11:39 UTC, epozine commented on vars/rpr_usdplugin_pipeline.groovy
> +                options.tests.split(" ").each { receiveFiles("${REF_PATH_PROFILE}/${it}", baselineDir) }
На мой взгляд читается хуже твой вариант кода
@Speedwag00n @GulDilin какое ваше мнение?

2021-02-18 11:56 UTC, testpassword commented on vars/rpr_usdplugin_pipeline.groovy
> +                options.tests.split(" ").each { receiveFiles("${REF_PATH_PROFILE}/${it}", baselineDir) }
Я думал, это относится к многострочным функциям, ибо за лишние скобки взгляд цепляется, а толку в них ноль. К тому же, в офиц. гайдлайне по кодестайлу Groovy ондострочный вариант для операций преобразования коллекций. Давай подождём остальных

2021-02-18 11:56 UTC, testpassword commented on vars/rpr_usdplugin_pipeline.groovy
> -        println(e.getMessage())
e.toString() и e.getMessage() выдают ровно одно и тоже, только первое с названием исключения, а второе без

2021-02-19 12:30 UTC, epozine approved these changes

2021-02-19 12:30 UTC, merged