Akulbako/usdviewer ums integration
luxteam/rpr_pipelines pull request #484
Opened 2021-02-17 08:38 UTC by testpassword

### Jira Ticket
- https://adc.luxoft.com/jira/browse/STVCIS-2077

### Purpose
- Integrate USDViewer for AMD Radeon ProRender to UMS

### Effect of change
- USDViewer builds now shows in UMS prod and dev

### Jenkins Builds
- https://rpr.cis.luxoft.com/job/DevRadeonProUSDViewer_with_UMS/52/
- https://ums.stvcis.luxoft.com/products/601bec9d746b2a28feb8fc85/602c30799f6bd1a18c6b32a5/artifacts
- https://ums.cistest.luxoft.com/products/601bdc23786633d8d356b235/602c3079154ca45ade4292f1/summary

2021-02-18 16:44 UTC, Speedwag00n requested changes

2021-02-18 16:44 UTC, Speedwag00n commented on vars/rpr_usdviewer_pipeline.groovy
> +        case "macOS":
Windows с большой буквы. Лучше сделать MacOS для единообразия

2021-02-18 16:44 UTC, Speedwag00n commented on src/universe/UniverseClient.groovy
> +            ],
Зачем такие отступы?

2021-02-18 16:44 UTC, Speedwag00n commented on src/universe/UniverseClient.groovy
> +                validResponseCodes: '200'
Тут тоже какие-то странные отступы

2021-02-18 16:44 UTC, Speedwag00n commented on src/universe/UniverseClient.groovy
> +                        "major": this.major_keys
Тут тоже какие-то странные отступы

2021-02-18 16:44 UTC, Speedwag00n commented on src/universe/UniverseClient.groovy
> +                        'tags': tags
Тут тоже какие-то странные отступы

2021-02-18 16:44 UTC, Speedwag00n commented on src/universe/UniverseClient.groovy
> +                    "jenkins_report": "${env.JENKINS_URL}job/${env.JOB_NAME}/${env.BUILD_NUMBER}"
Тут тоже какие-то странные отступы

2021-02-18 16:44 UTC, Speedwag00n commented on src/universe/UniverseClient.groovy
> +                        'suites': suites
Тут тоже какие-то странные отступы

2021-02-18 16:44 UTC, Speedwag00n commented on src/universe/UniverseClient.groovy
> +                    validResponseCodes: '0:599'
Тут тоже какие-то странные отступы

2021-02-18 16:44 UTC, Speedwag00n commented on src/universe/UniverseClient.groovy
> +                    ]
Тут тоже какие-то странные отступы

2021-02-18 16:44 UTC, Speedwag00n commented on src/universe/UniverseClient.groovy
> +                    validResponseCodes: '0:599'
Тут тоже какие-то странные отступы

2021-02-18 16:44 UTC, Speedwag00n commented on src/universe/UniverseClient.groovy
> +                    "SUCCESSFUL": "passed"
Тут тоже какие-то странные отступы

2021-02-18 16:44 UTC, Speedwag00n commented on src/universe/UniverseClient.groovy
> +                    'ts': timestamp
Тут тоже какие-то странные отступы

2021-02-18 16:44 UTC, Speedwag00n commented on src/universe/UniverseClient.groovy
> +                    validResponseCodes: '0:599'
Тут тоже какие-то странные отступы

2021-02-18 16:44 UTC, Speedwag00n commented on src/universe/UniverseClient.groovy
> +                    'problem_message': msg
Тут тоже какие-то странные отступы

2021-02-18 16:44 UTC, Speedwag00n commented on src/universe/UniverseClient.groovy
> +                    validResponseCodes: '0:599'
Тут тоже какие-то странные отступы

2021-02-18 16:44 UTC, Speedwag00n commented on vars/rpr_usdviewer_pipeline.groovy
> +                options.universeManager.sendToMINIO(options, "Windows", "..", buildName, false)
Думаю, пока лучше закомментить эту строчку. Если каждый раз отправлять такие большие артефакты, то за неделю закончится место. Нужно сперва логику удаления старых билдов и их артефактов починить

2021-02-18 16:44 UTC, Speedwag00n commented on vars/rpr_usdviewer_pipeline.groovy
> +                                    catch (Exception e) {
```suggestion
                                    } catch (Exception e) {
```

2021-02-18 16:44 UTC, Speedwag00n commented on vars/rpr_usdviewer_pipeline.groovy
> +                            println e.toString()
Не особо понятно, зачем эти изменения

2021-02-18 16:44 UTC, Speedwag00n commented on vars/rpr_usdviewer_pipeline.groovy
> +            catch (e) {
```suggestion
            } catch (e) {
```

2021-02-18 16:44 UTC, Speedwag00n commented on vars/rpr_usdviewer_pipeline.groovy
> +            catch(e) {
```suggestion
            } catch(e) {
```

2021-02-18 16:44 UTC, Speedwag00n commented on vars/rpr_usdviewer_pipeline.groovy
> +                else if (summaryReport.failed > 0) {
```suggestion
                } else if (summaryReport.failed > 0) {
```

2021-02-18 16:44 UTC, Speedwag00n commented on vars/rpr_usdviewer_pipeline.groovy
> +            catch(e) {
```suggestion
            } catch(e) {
```

2021-02-18 16:44 UTC, Speedwag00n commented on vars/rpr_usdviewer_pipeline.groovy
> +            catch (e) {
```suggestion
            } catch (e) {
```

2021-02-18 16:44 UTC, Speedwag00n commented on vars/rpr_usdviewer_pipeline.groovy
> +    catch (e) {
```suggestion
    } catch (e) {
```

2021-02-18 16:45 UTC, GulDilin commented on src/universe/UniverseClient.groovy
> -                'ts': timestamp
Поддерживаю

2021-02-18 17:32 UTC, GulDilin requested changes
Согласен с замечаниями Ильи

2021-02-19 12:52 UTC, testpassword commented on vars/rpr_usdviewer_pipeline.groovy
> +        case "macOS":
Я тут на официальное название опирался, поэтому с маленькой написал. Поправлю

2021-02-19 22:40 UTC, testpassword commented on vars/rpr_usdviewer_pipeline.groovy
> +                            println e.toString()
Да, то ли я запутался, то ли при мёржде что-то намутил

2021-02-24 14:45 UTC, Speedwag00n reviewed
Нужно обновить билды в описании после последних изменений

2021-02-24 14:45 UTC, Speedwag00n commented on vars/rpr_usdviewer_pipeline.groovy
> +                        "${NotificationConfiguration.REPORT_PUBLISHED}${summaryTestResults ? " Results: passed - ${summaryTestResults.passed}, failed - ${summaryTestResults.failed}, error - ${summary
По-моему не очень читаемо получилось. Лучше пожертвовать парой строчек на if, чем зрительно разбираться, куда относится какая кавычка. Хочу узнать, что скажут @epozine и @GulDilin

2021-02-24 14:45 UTC, Speedwag00n commented on vars/rpr_usdviewer_pipeline.groovy
> +    finally {
```suggestion
    } finally {
```

2021-02-25 09:48 UTC, epozine requested changes

2021-02-25 09:48 UTC, epozine commented on vars/rpr_usdviewer_pipeline.groovy
> +        GithubNotificator githubNotificator = new GithubNotificator(this, pullRequest)
Мы привязали данный код к инкременту версии, поэтому просьба здесь сделать тоже самое. 
Пример: https://github.com/luxteam/rpr_pipelines/blob/master/vars/rpr_mayaplugin_pipeline.groovy#L624
Логика инициализировать githubNotificator всегда в автоджобе, но не использовать в мануал и викли.

2021-02-25 09:48 UTC, epozine commented on vars/rpr_usdviewer_pipeline.groovy
> +                            def os = it.key
Давай оставим osName и gpuName.

2021-02-25 09:48 UTC, epozine commented on vars/rpr_usdviewer_pipeline.groovy
> +                        "${NotificationConfiguration.REPORT_PUBLISHED}${summaryTestResults ? " Results: passed - ${summaryTestResults.passed}, failed - ${summaryTestResults.failed}, error - ${summary
Мне в целом не нравятся конструкции подобного вида. 
Такая же использована например здесь https://github.com/luxteam/rpr_pipelines/pull/484/files#diff-2efd409aee70a6685b0e6ba48a7d6ea927d507636acb72b63b627f8a02851996R155
Я бы предпочел не использовать их в случаях когда конструкции большие или не использовать вовсе

2021-02-27 11:08 UTC, Speedwag00n commented on vars/rpr_usdviewer_pipeline.groovy
> +        GithubNotificator githubNotificator = new GithubNotificator(this, pullRequest)
К инкременту версии не получится привязаться, т.к. его просто нет в USDViewer.
Обсудили этот момента с Артемием, решили в просто делать проверку на существование env.BRANCH_NAME

2021-03-01 06:29 UTC, epozine approved these changes

2021-03-01 18:18 UTC, Speedwag00n approved these changes
По пайплайнам все хорошо

Однако почему-то нет картинок в билде. Судя по логам из jobs_launcher, они были отправлены. Вероятней всего, проблема на стороне UMS, поэтому здесь апрув поставлю
https://ums.cistest.luxoft.com/products/601bdc23786633d8d356b235/603a44cf6581ddcf6d7c7a6c/601d6686d0d5d8ec4a1fbae0/603a44cf6581ddcf6d7c7a6d

2021-03-04 09:28 UTC, epozine approved these changes

2021-03-04 09:29 UTC, merged