Vastrakhantsev/rs sample render
luxteam/rpr_pipelines pull request #523
Opened 2021-03-10 22:24 UTC by NISHIY-EKSDEE

### Jira Ticket
https://adc.luxoft.com/jira/browse/STVCIS-1300

### Purpose
Make sample render with low options to check if scene is correct and can be rendered.

### :warning: Notes for Reviewers
- Changed python3 implementation due to Baku error, now it works even there
- I'm not sure how to handle incorrect scenes. Now, if scene is incorrect, build is failed. The essence of the pipeline is in catching broken scenes, so sample render failure may be a success result. On other side, there may occur a machine error, so build must be failed. Is there any reason to implement this or failed builds are ok for us?
- Now if scene is incorrect, we continue trying to render it on other machine (I left it due to machine errors on Baku or Kabul). Should I stop the job after failed sampled render?
### :octocat: Related PR'S
https://gitlab.cis.luxoft.com/services/render_service/-/merge_requests/60

2021-03-15 06:31 UTC, Speedwag00n requested changes

2021-03-15 06:31 UTC, Speedwag00n commented on vars/render_service_scene_configuration.groovy
> +                    render_service_install_plugin(options["pluginLink"], options["pluginHash"], tool, "2.83", options.id, options.django_url)
Плагин инсталлится на 2.83 Blender, а не на ту версию блендера, которую указали

2021-03-15 06:31 UTC, Speedwag00n commented on vars/render_service_scene_configuration.groovy
> +                                        python3("launch_blender.py --tool \"2.91\" --django_ip \"${options.django_render_url}/\" --scene_name \"${scene_name}\" --id ${options.id_render} --min_samples
Тут тоже захардкожена версия Блендера

2021-03-17 07:10 UTC, NISHIY-EKSDEE commented on vars/render_service_scene_configuration.groovy
> +                                        python3("launch_blender.py --tool \"2.91\" --django_ip \"${options.django_render_url}/\" --scene_name \"${scene_name}\" --id ${options.id_render} --min_samples
Добавил версию Блендера, который используется для конфигурации, в blender_config \
https://gitlab.cis.luxoft.com/services/render_service/-/merge_requests/60/diffs#1a19dbd43fbd26c4cd98c427809b809e06d51435_6_6
Передаю ее вместе с параметром tool, как это сейчас сделано в рендер джобах

2021-03-26 12:02 UTC, Speedwag00n approved these changes

2021-03-29 15:00 UTC, epozine commented on vars/render_service_scene_configuration.groovy
> +    node("RenderService || Windows && Builder") {
Может лучше httpRequest использовать, чем занимать ноду?

2021-03-29 15:01 UTC, epozine commented on vars/render_service_scene_configuration.groovy
> +    node("RenderService || Windows && Builder") {
https://github.com/luxteam/rpr_pipelines/blob/master/src/universe/UniverseClient.groovy#L283
Пример

2021-03-31 07:21 UTC, NISHIY-EKSDEE commented on vars/render_service_scene_configuration.groovy
> +    node("RenderService || Windows && Builder") {
Убрал блок node перед отправкой номера билда и статуса, все работает
https://rpr.cis.luxoft.com/job/RenderService/job/TestRenderServiceSceneConfigurationJob/127/
https://rpr.cis.luxoft.com/job/RenderService/job/TestRenderServiceSceneConfigurationJob/128/

2021-04-07 16:13 UTC, epozine approved these changes

2021-04-07 17:56 UTC, merged