Add error messages for failed building of USD Viewer package
luxteam/rpr_pipelines pull request #534
Opened 2021-03-19 09:41 UTC by Speedwag00n

### Jira Ticket
* https://adc.luxoft.com/jira/browse/STVCIS-2150
### Purpose
* Add error messages for failed building of USD Viewer package
### Jenkins Builds
* Will be added later

2021-03-27 12:33 UTC, epozine requested changes

2021-03-27 12:33 UTC, epozine commented on vars/rpr_usdviewer_pipeline.groovy
> +        withNotifications(title: "Windows", options: options, artifactUrl: "${BUILD_URL}/artifact/${buildName}", configuration: NotificationConfiguration.BUILD_PACKAGE_USD) {
```suggestion
        withNotifications(title: "Windows", options: options, artifactUrl: "${BUILD_URL}/artifact/${buildName}", configuration: NotificationConfiguration.BUILD_PACKAGE_USD_VIEWER  {
```

2021-03-27 12:33 UTC, epozine commented on vars/rpr_usdviewer_pipeline.groovy
> +        withNotifications(title: "Windows", options: options, artifactUrl: "${BUILD_URL}/artifact/${buildName}", configuration: NotificationConfiguration.BUILD_PACKAGE_USD) {
тут опечатка?

2021-03-27 12:39 UTC, Speedwag00n commented on vars/rpr_usdviewer_pipeline.groovy
> +        withNotifications(title: "Windows", options: options, artifactUrl: "${BUILD_URL}/artifact/${buildName}", configuration: NotificationConfiguration.BUILD_PACKAGE_USD) {
Да, такой переменной, как указал ранее, нет в конфиге

2021-03-29 14:55 UTC, epozine submitted a review, later dismissed

2021-04-01 09:34 UTC, epozine approved these changes

2021-04-01 09:34 UTC, merged