Refactored hybrid notifications
luxteam/rpr_pipelines pull request #646
Opened 2021-06-29 08:00 UTC by NISHIY-EKSDEE

### Jira Ticket
https://adc.luxoft.com/jira/browse/STVCIS-2376

### Purpose
Use GithubNotificator implementation instead of legacy Jenkins extension

### :warning: Notes for Reviewers
[Test PR](https://github.com/Radeon-Pro/RPRHybrid/pull/855)
### Jenkins Builds
https://rpr.cis.luxoft.com/job/DevJobs/job/DevRadeonProRender-Hybrid/view/change-requests/job/PR-855/16/

2021-07-01 09:35 UTC, Speedwag00n approved these changes
С самим ПРом с точки зрения задачи все хорошо
Проблема есть с Github API. Тут оказалось, что у них сейчас актуальны и statuses, и checks (мне казалось ранее, что statuses depricated):
https://docs.github.com/en/enterprise-server@3.0/github/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/about-status-checks

Нужно будет обсудить, что мы хотим использовать в будущем

2021-07-01 09:35 UTC, Speedwag00n commented on src/GithubNotificator.groovy
> +                                            target_url: targetUrl])
```suggestion
                                            target_url: targetUrl]
            )
```

2021-07-01 09:46 UTC, Speedwag00n submitted a review, later dismissed

2021-07-21 13:23 UTC, Speedwag00n requested changes
Мне нравится решение инициализировать статус чеки в пайплайне, а не в GithubNotificator. Слишком уж отличается пайплайна Гибрида от остальных проектов по структуре.
Оставил одно замечание по именованию чеков. В остальном со всем согласен

2021-07-21 13:23 UTC, Speedwag00n commented on vars/rpr_hybrid_pipeline.groovy
> +            String title = "${asicName}-${osName}"
Во всех проектах в заголовке статуса строка по шаблону: Операционка-Карточка
Тут получится наоборот: Карточка-Операционка
Лучше привести к одному виду, как во всех текущих проектах, чтобы не было путаницы

2021-07-21 20:40 UTC, NISHIY-EKSDEE commented on vars/rpr_hybrid_pipeline.groovy
> +            String title = "${asicName}-${osName}"
Наоборот, в гибриде наткнулся, что ОС и ГПУ были перепутаны.
[Инициализация чеков](https://github.com/luxteam/rpr_pipelines/blob/master/src/GithubNotificator.groovy#L130)
[Пример в Блендере](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/pull/335/checks?check_run_id=3116374279)
[Пример в Майе](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderMayaPlugin/pull/223/checks?check_run_id=3080913839)

2021-07-22 05:27 UTC, Speedwag00n commented on vars/rpr_hybrid_pipeline.groovy
> +            String title = "${asicName}-${osName}"
Тогда это в порядке

2021-07-22 05:27 UTC, Speedwag00n approved these changes

2021-07-22 13:42 UTC, epozine approved these changes

2021-07-22 13:42 UTC, merged