Avk/crref
luxteam/rpr_pipelines pull request #860
Opened 2022-02-07 13:28 UTC by Flame0n

### Jira Ticket

### Purpose

### Effect of change

### Technical steps
- [x] Step 1
- [x] Step 2
- [ ] Step 3

### :warning: Notes for Reviewers

### :octocat: Related PR'S

### Jenkins Builds

2022-03-10 06:10 UTC, Speedwag00n requested changes

2022-03-10 06:10 UTC, Speedwag00n commented on vars/rpr_core_pipeline.groovy
> +    options.stageName = options.stageName.replace("--", "-")
Что за кейс, когда идет -- в название стадии?
Можно ли сделать по аналогии с Блендером/Майей или есть какие-то важные отличия?
https://github.com/luxteam/rpr_pipelines/blob/master/vars/rpr_blenderplugin_pipeline.groovy#L103

2022-03-10 10:27 UTC, Flame0n commented on vars/rpr_core_pipeline.groovy
> +    options.stageName = options.stageName.replace("--", "-")
По факту я в options.testsList лью данные типа: ["-Hybrid", "-Northstar64"].
В майке/блендере такое: ["*TESTS*-Hybrid", "*TESTS*-Northstar"],
Если использовать как в майке и блендере, то мне из названия файлов нужно удалять группу каждый раз.
А в моем случае я просто удаляю "--" из названия фалов. 
Например из таких: "AMD_WX9100-Windows--Hybrid/Test-AMD_WX9100-Windows_0.log"
Если уж в обоих случаях мы парсим строку, не лучше ли тогда решение с меньшим количеством кода?

2022-03-11 09:12 UTC, Piromancer approved these changes

2022-03-11 17:08 UTC, merged